apiVersion: v1
kind: Service
metadata:
  labels:
    app: content-api
  name: content-api
spec:
  ports:
    - name: "8002"
      port: 8002
      targetPort: 80
  selector:
    app: content-api
status:
  loadBalancer: {}
