apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: content-api
  name: content-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: content-api
  strategy: {}
  template:
    metadata:
      labels:
        app: content-api
    spec:
      containers:
        - image: content
          name: gtm-container-content
          ports:
            - containerPort: 80
          resources: {}
          imagePullPolicy: Never
      restartPolicy: Always
status: {}
