apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway
  name: gateway
spec:
  type: LoadBalancer 
  ports:
    - name: "8001"
      port: 8001
      targetPort: 80
      nodePort: 30100
  selector:
    app: gateway
status:
  loadBalancer: {}
