apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: product-api
  name: product-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-api
  strategy: {}
  template:
    metadata:
      labels:
        app: product-api
    spec:
      containers:
        - image: product
          name: gtm-container-product
          ports:
            - containerPort: 80
          resources: {}
          imagePullPolicy: Never
      restartPolicy: Always
status: {}
